import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { classify, extractWebpFrames, readPng, type Frame } from '../scripts/spell-decode.ts';
import { normaliseMask, renderSpellShape, type Mask } from '../src/area.ts';

const dir = fileURLToPath(new URL('./fixtures/spell-frames/', import.meta.url));

/** Fixtures are generated by scripts/make-golden-frames.ts; deltas are fully opaque. */
const frame = (name: string): Frame => {
  const { width, height, pixels } = readPng(readFileSync(`${dir}${name}.png`));
  return { x: 0, y: 0, width, height, pixels };
};
const ascii = (m: Mask): string => {
  const rows: string[] = [];
  for (let r = 0; r < m.height; r += 1) {
    rows.push(m.cells.slice(r * m.width, (r + 1) * m.width).map((c) => (c ? '#' : '.')).join(' '));
  }
  return rows.join('\n');
};

const CONE = [
  '. . # . .',
  '. # # # .',
  '. # # # .',
  '# # # # #',
].join('\n');

test('a cone classifies to a cone, not to its bounding box', () => {
  const mask = classify(frame('cone-plate'), [frame('cone-delta')]);
  assert.equal(ascii(mask), CONE);
  assert.equal(mask.cells.filter((c) => c === 1).length, 12);
});

/**
 * The original bug, pinned. Delta frames redraw the opaque floor, so treating any
 * non-transparent pixel as effect marks every tile the frame covers. `tolerance: -1`
 * makes every opaque pixel "differ" and reproduces it exactly - no production
 * predicate seam needed, and none should be added.
 *
 * This assertion is only meaningful because the fixture's delta is fully opaque
 * across the canvas. A transparent-background fixture would pass under both
 * classifiers and prove nothing.
 */
test('the opacity classifier fills the bounding box, and is therefore excluded', () => {
  const broken = classify(frame('cone-plate'), [frame('cone-delta')], { tolerance: -1 });
  assert.notEqual(ascii(broken), CONE, 'if this matches, the fixture is not opaque');
  assert.equal(broken.cells.every((c) => c === 1), true, 'every tile the frame covers');
  assert.equal(broken.cells.filter((c) => c === 1).length, 20);
});

test('each shape family decodes to its expected cells', () => {
  const cases: Array<[string, string, number]> = [
    ['strike', '. . .\n. # .\n. . .', 1],
    ['square3', '# # #\n# # #\n# # #', 9],
    ['beam', '. # .\n. # .\n. # .\n. # .\n. # .\n. . .\n. . .', 5],
  ];
  for (const [name, expected, tiles] of cases) {
    const mask = classify(frame(`${name}-plate`), [frame(`${name}-delta`)]);
    assert.equal(ascii(mask), expected, name);
    assert.equal(mask.cells.filter((c) => c === 1).length, tiles, name);
  }
});

test('the 37-tile circle decodes cell for cell', () => {
  const mask = classify(frame('circle-plate'), [frame('circle-delta')]);
  assert.equal(mask.cells.filter((c) => c === 1).length, 37);
  assert.equal(ascii(mask), [
    '. . # # # . .',
    '. # # # # # .',
    '# # # # # # #',
    '# # # # # # #',
    '# # # # # # #',
    '. # # # # # .',
    '. . # # # . .',
  ].join('\n'));
});

/**
 * Every other golden uses a single delta, so an implementation that took the first
 * frame, or unioned all frames, would pass them all. Here the frames differ and the
 * union differs from the winning frame.
 */
test('the frame with the most affected tiles wins, not the first or the union', () => {
  const plate = frame('multi-plate');
  const small = frame('multi-delta-small');
  const big = frame('multi-delta-big');
  const mask = classify(plate, [small, big]);
  assert.equal(ascii(mask), CONE, 'the larger frame must win');

  // First-frame selection would differ.
  assert.notEqual(ascii(classify(plate, [small])), CONE);

  // And so would a union. `small` lights [0,0], which the cone does not, so the
  // union is strictly larger than either frame. Without that cell the union equals
  // `big` and this assertion is vacuous - which is exactly what it was before.
  const union = [
    '# . # . .',
    '. # # # .',
    '. # # # .',
    '# # # # #',
  ].join('\n');
  assert.notEqual(ascii(mask), union, 'the winning frame is not the union of frames');
  assert.ok(ascii(classify(plate, [small])).startsWith('# .'), 'small lights a cell outside the cone');
});

test('offsets place a delta, and ignoring them moves every tile', () => {
  const plate = frame('cone-plate');
  const delta = frame('strike-delta');
  const at = (x: number, y: number) => ascii(classify(plate, [{ ...delta, x, y }]));
  assert.notEqual(at(0, 0), at(32, 0), 'a horizontal offset must move the mask');
  assert.notEqual(at(0, 0), at(0, 32), 'a vertical offset must move the mask');
});

test('extractWebpFrames reads real frame offsets, non-zero on both axes', () => {
  // A real wiki animation, not a synthesised container: a container this code also
  // wrote would encode the same offset convention on both sides and could agree on
  // a wrong answer. Berserk1.gif, CC BY-SA TibiaWiki, CipSoft artwork.
  const frames = extractWebpFrames(readFileSync(`${dir}berserk1.webp`));
  assert.equal(frames.length, 10);
  assert.deepEqual([frames[0]!.x, frames[0]!.y], [0, 0], 'frame 0 is the full plate');
  assert.deepEqual([frames[1]!.x, frames[1]!.y], [44, 44]);
  assert.deepEqual([frames[2]!.x, frames[2]!.y], [42, 42]);
  assert.equal(
    frames.slice(1).every((f) => f.x > 0 && f.y > 0), true,
    'every delta offset is non-zero on both axes, so a hardcoded zero fails',
  );
  assert.ok(frames.every((f) => f.payload.length > 0));
});

test('normaliseMask crops, so padding alone is not a disagreement', () => {
  // TibiaWiki's two Energy Beam animations decode to a cell-identical 1x5 on
  // canvases of 3x8 and 3x9. Comparing raw canvases calls that a conflict.
  const a: Mask = { width: 3, height: 8, cells: Array.from({ length: 24 }, (_, i) => (i % 3 === 1 && i < 18 && i > 2 ? 1 : 0)) };
  const b: Mask = { width: 3, height: 9, cells: Array.from({ length: 27 }, (_, i) => (i % 3 === 1 && i < 21 && i > 5 ? 1 : 0)) };
  assert.notDeepEqual(a.cells, b.cells, 'the raw canvases differ');
  assert.deepEqual(normaliseMask(a), normaliseMask(b), 'the shapes do not');
  assert.equal(normaliseMask(a).width, 1);
});

test('renderSpellShape emits two glyphs and rejects malformed input', () => {
  const shape = renderSpellShape({
    width: 3, height: 1, cells: [0, 1, 0],
    sourceImage: 'X.gif', sourceUrl: 'https://example.invalid/X.gif', corroborated: true,
  });
  assert.equal(shape.ascii, '. # .');
  assert.equal(shape.affectedTiles, 1);
  assert.equal(shape.derivedFrom, 'animation');
  assert.ok(!/[@*]/.test(shape.ascii), 'the decode cannot recover caster or target tiles');

  const base = { sourceImage: 'X.gif', sourceUrl: 'u', corroborated: false };
  assert.throws(() => renderSpellShape({ width: 2, height: 1, cells: [0, 1, 0], ...base }), /cells for a/);
  assert.throws(() => renderSpellShape({ width: 2, height: 1, cells: [0, 3], ...base }), /must be 0 or 1/);
  assert.throws(() => renderSpellShape({ width: 0, height: 1, cells: [], ...base }), /positive integers/);
});

test('tsconfig typechecks the scripts that hold the decoder', () => {
  // scripts/spell-decode.ts is only typechecked because `include` matches its
  // extension. The facts script broke `pnpm test` once for exactly this reason,
  // one extension over, and nothing asserted the coverage.
  const cfg = readFileSync(fileURLToPath(new URL('../tsconfig.json', import.meta.url)), 'utf8');
  const include = JSON.parse(cfg.replace(/\/\/.*$/gm, '')).include as string[];
  assert.ok(include.includes('scripts/**/*.ts'), `include is ${JSON.stringify(include)}`);
  assert.ok(include.includes('scripts/**/*.mjs'));
});
